---
- hosts: "machine"
  tasks:
        - name: Status of AuthoringTool directory
          stat: path={{at_home}}
          register: directory_status

        - name: Remove AuthoringTool directory 
          file: state=absent path={{at_home}}
          when: directory_status.stat.exists

        - name: Copy zip file to server
          copy: src=content-editor.zip dest={{user_home}}/ owner={{user}} group={{user}} mode=0774

        - name: Create AuthoringTool directory
          file: path={{at_home}} owner={{server_runs_as}} group={{server_runs_as}} state=directory

        - name: Unarchive zip file
          unarchive: src={{user_home}}/content-editor.zip dest={{at_home}} copy=no owner={{server_runs_as}} group={{server_runs_as}}